services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - CONFIG_PATH=config/config.yaml
      - INIT_PATH=internal/storage/init/init.sql
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - db
    command: go run ./cmd/songLibrary/main.go

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: